# ndarray

- *ndarray* for n dimension array
- 也就是**多维数组**

In [1]:
import numpy as np

## 1.

### 1.1 Generate an array

In [2]:
a1 = np.array([1, 2, 3, 4])
print(a1)

[1 2 3 4]


### 1.2 define complex number

In [3]:
a2 = np.array([1, 2, 3, 4], dtype=complex)
print(a2)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


### 1.3 reshape

In [4]:
a3 = np.array([1, 2, 3, 4], dtype=complex).reshape((2, 2))
print(a3)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


## 2.

### 2.1 2 rows and 3 columns

In [6]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


## 3.

### 3.1 "zero" matrix

In [7]:
c1 = np.zeros((2, 2))
print(c1)

[[0. 0.]
 [0. 0.]]


### 3.2 "one" matrix

In [8]:
c2 = np.ones((2, 2))
print(c2)

[[1. 1.]
 [1. 1.]]


### 3.3 empty matrix

In [9]:
c3 = np.empty((2, 3))
print(c3)

[[0. 0. 0.]
 [0. 0. 0.]]


## 4.

### 4.1 eye for unit matrix

In [10]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 5. arange

### 5.1 arange 的用法与 range 相似

In [11]:
d1 = np.arange(0, 10, 2)
print(d1)

[0 2 4 6 8]


### 5.2 关于精度

- 由于有限的浮点精度，获得的元素个数可能与预期有些出入

In [12]:
d2 = np.arange(0, 3, 0.2)
print(d2)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8]


## 6.

### 6.1 linspace

In [13]:
g = np.linspace(0, 3, 10)
print(g)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
