# ndarray

- attribute

In [1]:
import numpy as np

## 1.

### 1.1 生成一个数组，并按 3 行 4 列打印

In [2]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 1.2 数组的维度（轴）的个数

In [3]:
print(a.ndim)

2


### 1.3 数组的形状

In [5]:
print(a.shape)

(3, 4)


### 1.4 数组中元素的个数

In [6]:
print(a.size)

12


### 1.5 数组中元素的类型

In [7]:
print(a.dtype)

int32


### 1.6 数组中每个元素所占的字节数

In [8]:
print(a.itemsize)

4


### 1.7 存储数组内元素内存缓冲区地址

- 一般不用

In [9]:
print(a.data)

## 2.

### 2.1 生成一个较大的数组

- 按 100 行 100 列打印
- 对较大的数组，默认以省略的形式打印

In [10]:
b1 = np.arange(10000).reshape((100, 100))
print(b1)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


### 2.2 set_printoptions 之后

- 数组可以按自己的设置打印

In [12]:
np.set_printoptions(threshold=10000)
b2 = np.arange(10000).reshape((100, 100))
print(b2)  # 数字很多，我这里省了。。。