# ndarray

- calculate

In [1]:
import numpy as np

## 1.

In [2]:
a = [i+2 for i in range(10)]
print(a)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


## 2.

### 2.1

In [4]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


### 2.2

In [5]:
print(b + 2)

[ 2  3  4  5  6  7  8  9 10 11]


### 2.3

In [6]:
print(b * 2)

[ 0  2  4  6  8 10 12 14 16 18]


## 3.

### 3.1

In [7]:
c = np.arange(12).reshape((3, 4))
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 3.2

In [8]:
print(c ** 2)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


### 3.3

In [9]:
print(np.sin(c))

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


### 3.4

In [10]:
print(np.cos(c))

[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]


## 4.

### 4.1

In [11]:
print(c < 5)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


## 5. 小结

- 当对 ndarray 使用各种算术运算符时
    - numpy 会将其应用于数组的每一个元素
    - 计算完成后返回一个与原来形状相同的 ndarray