# ndarray

- matrix multiplication

In [1]:
import numpy as np

## 1.

In [2]:
a = np.arange(12).reshape((3, 4))
b = np.arange(12).reshape((4, 3))

### 1.1

In [3]:
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 1.2 错误的写法

In [4]:
print(a * b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

### 1.3 正确的写法1

In [5]:
print(a.dot(b))

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


### 1.4 正确的写法2

- same as *1.3*

In [6]:
print(a @ b)

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


## 2.

-  matrix in numpy must be 2d

In [7]:
c = np.matrix(a)
d = np.matrix(b)

### 2.1

In [8]:
print(type(c))
print(type(d))

<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.matrixlib.defmatrix.matrix'>


### 2.2

In [9]:
print(c * d)

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


## 3. 小结

- numpy 有矩阵类
    - 但还是尽量使用 ndarray 为好
    - 不要混用！