# ndarray

- index
- slice
- iterator

In [1]:
import numpy as np

## 1.

In [2]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
print(a[1])
print(a[2:8])
print(a[2:8:2])
print(a[::-1])

1
[2 3 4 5 6 7]
[2 4 6]
[11 10  9  8  7  6  5  4  3  2  1  0]


## 2.

### 2.1

In [4]:
b = np.arange(12).reshape((4, 3))
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
print(b[0])
print(b[1][2])
print(b[1:3, :0:-1])  # [第 1 行, 第 3 行), [最后一列, 第 0 列), 倒序

[0 1 2]
5
[[5 4]
 [8 7]]


### 2.2

In [6]:
for i in b:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [7]:
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
