# ndarray

- operation

In [1]:
import numpy as np

## 1.

In [2]:
a = np.arange(12)
b = a.reshape((3, 4))

### 1.1

In [3]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 1.2

In [4]:
print(id(a))
print(id(b))

1513869277904
1513869278224


## 2.

In [5]:
a.resize((3, 4))

print(a)
print(id(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1513869277904


## 3.

### 3.1 转置

In [6]:
print(a.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 3.2 展开

#### 3.2.1 ravel()

- 返回的是原数组的一个视图(view)，会对原数组产生影响

In [7]:
print(a.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### 3.2.2 flatten()

- 返回的是一个新数组

In [8]:
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 4.

### 4.1

In [9]:
print(a.flat)

### 4.2

In [10]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
