# hstack & vstack

In [1]:
import numpy as np

## 1.

In [2]:
a = np.arange(4)
b = np.arange(4, 8)

### 1.1

In [3]:
print(a)
print(b)

[0 1 2 3]
[4 5 6 7]


### 1.2 hstack

In [4]:
print(np.hstack((a, b)))

[0 1 2 3 4 5 6 7]


### 1.3 vstack

In [6]:
print(np.vstack((a, b)))

[[0 1 2 3]
 [4 5 6 7]]


## 2.

In [7]:
c = np.arange(4).reshape((2, 2))
d = np.arange(4, 8).reshape((2, 2))

### 2.1

In [10]:
print(c)
print(d)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


### 2.2 形状

- 在堆叠的维度之外的其他维度上，形状必须相同

In [8]:
print(np.hstack((c, d)))

[[0 1 4 5]
 [2 3 6 7]]


In [9]:
print(np.vstack((c, d)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
