# concatenate

In [1]:
import numpy as np

## 1.

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

### 1.1

In [3]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]]


### 1.2

In [4]:
print(a.shape)
print(b.shape)

(2, 2)
(1, 2)


## 2.

In [5]:
c = np.concatenate((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]]


## 3.

In [6]:
d = np.concatenate((a, b.T), axis=1)
print(d)

[[1 2 5]
 [3 4 6]]


## 4.

- np.hstack() and np.vstack() can't point axis