# newaxis

In [1]:
import numpy as np

## 1.

In [2]:
a = np.arange(4)
print(a)
print(a.shape)

[0 1 2 3]
(4,)


## 2.

In [3]:
b = a.reshape((4, 1))
print(b)
print(b.shape)

[[0]
 [1]
 [2]
 [3]]
(4, 1)


## 3.

In [4]:
c = a[:, np.newaxis]
print(c)
print(c.shape)

[[0]
 [1]
 [2]
 [3]]
(4, 1)


## 4.

In [6]:
d = a[np.newaxis, ]
print(d)
print(d.shape)

[[0 1 2 3]]
(1, 4)


## 5.

In [7]:
e = a.reshape((2, 2))
print(e)

[[0 1]
 [2 3]]


In [8]:
print(e[np.newaxis, ].shape)
print(e[:, np.newaxis].shape)

(1, 2, 2)
(2, 1, 2)


In [9]:
print(e[:, :, np.newaxis].shape)
print(e[:, :, None].shape)

(2, 2, 1)
(2, 2, 1)
