# colstack & rowstack

In [1]:
import numpy as np

## 1. Stack 1-D arrays as columns into a 2-D array

In [3]:
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
c1 = np.column_stack((a1, b1))
print(c1)

[[1 4]
 [2 5]
 [3 6]]


## 2.

In [4]:
a2 = np.array([[1, 2, 3], [3, 4, 5]])
b2 = np.array([[4, 5, 6], [6, 7, 8]])
c2 = np.column_stack((a2, b2))
print(c2)

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]


## 3.

In [5]:
c3 = np.row_stack((a2, b2))
print(c3)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]


## 4. 上方的 row_stack 与 vstack 的效果一样

In [6]:
c4 = np.vstack((a2, b2))
print(c4)

[[1 2 3]
 [3 4 5]
 [4 5 6]
 [6 7 8]]
